### ISSUE TITLE
Request option --temp

### ISSUE THREAD

**Issue by illaxaer** [metalefty/X11RDP-RH-Matic#12]
Can you add option for temp location? For building x11rdp it need more than 1Gb free space in /tmp.
But /tmp is less 1Gb, if RAM size =< 2Gb and I must set TMPDIR in bash for this script.

**Comment by metalefty** [comment]
Good point. Can't argue with that.

**Comment by metalefty** [comment]
I've pushed `--tmpdir` option to develop branch. Could you please test it?

For example:
`./X11RDP-RH-Maric.sh --nox11rdp --noinstall --tmpdir # not specifying any directories`
`./X11RDP-RH-Maric.sh --nox11rdp --tmpdir  --noinstall # not specifying any directories`
`./X11RDP-RH-Maric.sh --nox11rdp --noinstall --tmpdir /var/tmp`
`./X11RDP-RH-Matic.sh --nox11rdp --noinstall --tmpdir /non/existent/directory/speciffied`
`./X11RDP-RH-Matic.sh --nox11rdp --noinstall --tmpdir /root # no write permission directory`

If you come with up other possible patterns of options, please test them.

**Comment by illaxaer** [comment]
1. "Invalid working directory '' specified."
2. "Invalid working directory '--noinstall' specified."
3. Works good. Used /var/tmp as temp dir.
4. "Invalid working directory '/non/existent/directory/speciffied' specified."
5. "mktemp: failed to create directory via template '/root/tmp.XXXXXXXXXX.X11RDP-RH-Matic': Permission denied".

**Comment by metalefty** [comment]
1, 2, 4, 5 should fail. It looks properly working.
