### ISSUE TITLE
xrdp-sesman.service failed

### ISSUE THREAD

**Issue by illaxaer** [metalefty/X11RDP-RH-Matic#13]
xrdp-sesman.service - xrdp session manager
   Loaded: loaded (/usr/lib/systemd/system/xrdp-sesman.service; disabled)
   Active: failed (Result: exit-code) since Чт 2015-04-16 17:00:26 MSK; 30s ago
  Process: 18203 ExecStart=/usr/sbin/xrdp-sesman $SESMAN_OPTIONS (code=exited, status=203/EXEC)

Apr 16 17:00:26 localhost.localdomain systemd[18203]: Failed at step EXEC spawning /usr/sbin/xrdp-sesman: Permission denied
Apr 16 17:00:26 localhost.localdomain systemd[1]: xrdp-sesman.service: control process exited, code=exited status=203
Apr 16 17:00:26 localhost.localdomain systemd[1]: Failed to start xrdp session manager.
Apr 16 17:00:26 localhost.localdomain systemd[1]: Unit xrdp-sesman.service entered failed state.
Apr 16 17:00:26 localhost.localdomain systemd[1]: xrdp-sesman.service failed.
System: Fedora 21

On my other Fedora 21 this problem was fixed by coping files /usr/sbin/xrdp* to /usr/bin, and later back.

**Comment by itamarjp** [comment]
this is related to selinux, setenforce 0 is a workarround for it.

**Comment by metalefty** [comment]
Can neutrinolabs/xrdp#260 fix this?

**Comment by itamarjp** [comment]
no, this issue is related to selinux, take a look on this.

https://bugzilla.redhat.com/show_bug.cgi?id=1177202

**Comment by metalefty** [comment]
Made a workaround d2a0c39afd1117de2184f5a269d160ed5c19d9ce.
