### ISSUE TITLE
withjpeg option removes --enable-fuse argument

### ISSUE THREAD

**Issue by therevoman** [metalefty/X11RDP-RH-Matic#14]
While using this script I discovered my clipboard would not work properly if I enabled the --withjpeg option.  It turns out the variable is misnamed in the switch statement.  There's a missing underscore.

    --withjpeg)
      XRDP_CONFIGURE_ARGS="$XRDPCONFIGURE_ARGS --enable-jpeg"
      XRDP_BUILD_DEPENDS="$XRDP_BUILD_DEPENDS libjpeg-turbo-devel"
      ;;

should be 

    --withjpeg)
      XRDP_CONFIGURE_ARGS="$XRDP_CONFIGURE_ARGS --enable-jpeg"
      XRDP_BUILD_DEPENDS="$XRDP_BUILD_DEPENDS libjpeg-turbo-devel"
      ;;

**Comment by metalefty** [comment]
Fixed, thanks!
