### ISSUE TITLE
xorg driver not building - xrdp issue 298

### ISSUE THREAD

**Issue by vlaero** [metalefty/X11RDP-RH-Matic#18]
Can the fix for the issue described here be merged? https://github.com/neutrinolabs/xrdp/issues/298
I'm having trouble getting the xorg module building on Centos 7.2 with the latest package updates.

From what I can read of the above xrdp issue the fix has been merged into the xrdp master branch.

**Comment by metalefty** [comment]
Generally speaking, we don't need to merge it because RH-Matic always clones xrdp repository.
Anyway, I will test the build.

**Comment by metalefty** [comment]
It just depends on upstream.  I’d appreciate it if you could ask Jay to update xorgxrdp submodule in master branch.
