### ISSUE TITLE
rpmbuild --rebuild of x11rdp SRPM fails

### ISSUE THREAD

**Issue by unixpro1970** [metalefty/X11RDP-RH-Matic#19]
Please fix X11RDP-RH-Matic/SPECS/x11rdp.spec.in so others will not have this problem.

A) Problem:
Note: When the cache directory does not exist it will cause rpmbuild --rebuild of x11rdp SRPM to fail. The fix is to check if the cache directory exists before attempting the find -delete command
Ex: rpmbuild --rebuild x11rdp-0.9.0.git9c48b7b+master-1.el6.src.rpm 

The error message is as follows:

+ find /root/rpmbuild/BUILDROOT/x11rdp-0.9.0.gitee89984+master-1.el6.sparc64/opt/X11rdp/var/cache -delete
find: `/root/rpmbuild/BUILDROOT/x11rdp-0.9.0.gitee89984+master-1.el6.sparc64/opt/X11rdp/var/cache': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.ByW2pt (%install)

B) Solution: (after this modification x11rdp rebuilds fine )

Change  line 46:

From:
find %{buildroot}%%X11RDPBASE%%/var/cache -delete

To:
[ -d  %{buildroot}%%X11RDPBASE%%/var/cache ] && find %{buildroot}%%X11RDPBASE%%/var/cache -delete

**Comment by metalefty** [comment]
Pushed the fix on develop branch, thanks.  Can you confirm?

Please keep this issue open after your confirmation.

**Comment by unixpro1970** [comment]
No problem.  Will do so asap, once confirmed how long before the change is
merged to master?



Pushed the fix on develop branch, thanks.  Can you confirm?

Please keep this issue open after your confirmation.


Reply to this email directly or view it on GitHub
<https://github.com/metalefty/X11RDP-RH-Matic/issues/19#issuecomment-1716632
97> .

**Comment by metalefty** [comment]
No longer than a week.

**Comment by unixpro1970** [comment]
Just re-confirmed my change works, re-compiled source and performed rpmbuild
rebuild  without any problems.
