### ISSUE TITLE
RHEL 7.2 not showing desktop

### ISSUE THREAD

**Issue by therevoman** [metalefty/X11RDP-RH-Matic#22]
I thought I'd step into uncharted territory today by adding XRDP to a RHEL 7.2 dev VM.  
The build was successful using the command line:
`./X11RDP-RH-Matic.sh --branch devel --nox11rdp --with-xorg-driver`

I generated keys, modified the /etc/pam.d/xserver file and the service stars.  When logging in I am presented with a prompt for my username/password but when I select the option I added for the xorg driver, I get a blue screen but the Gnome desktop never comes up.

I'm attaching files that might be helpful.  Also, the log files were gathered by running /usr/sbin/xrdp -ns and /usr/sbin/xrdp-sesman -ns

Thanks in advance.

[xrdp console log.txt](https://github.com/metalefty/X11RDP-RH-Matic/files/126989/xrdp.console.log.txt)

[xrdp-sesman console log.txt](https://github.com/metalefty/X11RDP-RH-Matic/files/126990/xrdp-sesman.console.log.txt)

[xrdp.ini.txt](https://github.com/metalefty/X11RDP-RH-Matic/files/126993/xrdp.ini.txt)
[sesman.ini.txt](https://github.com/metalefty/X11RDP-RH-Matic/files/126994/sesman.ini.txt)

**Comment by metalefty** [comment]
This is odd.  24bit-color should be supported now.
But anyway, let's see the result of other bpps 15bit 16 bit, or 32bit.

```
[20160211-12:14:37] [WARN ] [v0:260] connection aborted: unsupported bpp: 24
```

**Comment by metalefty** [comment]
You're using devel branch.  Probably, recent change on neutrinolabs/xrdp#316 does affect.
Not an RH-Matic issue.

**Comment by metalefty** [comment]
Fixed in xrdp devel branch [ac901fd](https://github.com/neutrinolabs/xrdp/commit/ac901fd283e2cd418740ea1445b41502aa57ccb5). Can you try it again?
If it goes well, please close.

**Comment by therevoman** [comment]
I won't be able to try it again until Tuesday, but I will close the issue if it is fixed.

Two things.  First I am trying to use the xorg driver not vnc as the back end.  Is that xrdp bug related?
Second, Where would I set the color depth?  I played around with the ini files but it didn't seem to matter what I set.

**Comment by metalefty** [comment]
Color depth is in your client.

**Comment by therevoman** [comment]
Thanks for fixing that bug in the xrdp project!!  I can now connect, after a bit of hacking.  

I'll post the issue I ran across separately.
