### ISSUE TITLE
xrdp-pam-auth.patch invalid in RHEL 7 & with new xrdp dev branch

### ISSUE THREAD

**Issue by therevoman** [metalefty/X11RDP-RH-Matic#23]
In the new xrdp develop branch the instfiles/pam.d/xrdp-sesman file appears to have been brokenup or renamed so the xrdp.spec.in Patch0 step is failing.  Once I commented out '%patch0' the build completed successfully and I was able to connect.

[devuser@UTLXDEV173 BUILD]$ find . -iname "xrdp-sesman"*
./neutrinolabs-xrdp-3934be9/instfiles/pam.d/xrdp-sesman.password-auth
./neutrinolabs-xrdp-3934be9/instfiles/pam.d/xrdp-sesman.common
./neutrinolabs-xrdp-3934be9/instfiles/pam.d/xrdp-sesman.other
./neutrinolabs-xrdp-3934be9/instfiles/xrdp-sesman.service
./neutrinolabs-xrdp-3934be9/docs/man/xrdp-sesman.8
./neutrinolabs-xrdp-09a69fb/sesman/.libs/xrdp-sesman
./neutrinolabs-xrdp-09a69fb/sesman/xrdp-sesman
./neutrinolabs-xrdp-09a69fb/instfiles/pam.d/xrdp-sesman.other
./neutrinolabs-xrdp-09a69fb/instfiles/pam.d/xrdp-sesman
./neutrinolabs-xrdp-09a69fb/instfiles/xrdp-sesman.service
./neutrinolabs-xrdp-09a69fb/docs/man/xrdp-sesman.8

**Comment by metalefty** [comment]
Yes, patch0 is no longer needed for xrdp devel brach but needed for other branches.
I pushed fix to [upstream-deve-pam](https://github.com/metalefty/X11RDP-RH-Matic/tree/upstream-devel-pam) branch of X11RDP-RH-Matic.

Could you try `upstream-devel-pam` branch both `--branch devel` and `--branch master`?
If you can spare time for test, please confirm you can pass authentication in both branch. 

It it looks good, I will merge it.

**Comment by therevoman** [comment]
Just finished testing devel branch.  Looks good.  Might be a few days before I get time to test master.

**Comment by therevoman** [comment]
Ok.  Just tested master and it is working.   

Thanks for the help
