### ISSUE TITLE
387a865 breaks build on hosts without Xorg installed

### ISSUE THREAD

**Issue by nktl** [metalefty/X11RDP-RH-Matic#25]
Build fails on 387a865 and later when Xorg is not installed on the build server (as it tries to inject Xorg binary with custom permission) - it should probably be added as a dependency.

Additionally, it looks like assumption is made that server that builds the RPM is the one that is going to run xrdp - which is not always the case. This nosuid Xrdp binary creation should probably be moved to rpm installation script so X version is always consistent with the version on the host.

**Comment by metalefty** [comment]
Thanks, I forgot to change dependency. Here's what I Intended to.
```
diff --git a/SPECS/xorg-x11-drv-xrdp.spec.in b/SPECS/xorg-x11-drv-xrdp.spec.in
index 355b17f..0557662 100644
--- a/SPECS/xorg-x11-drv-xrdp.spec.in
+++ b/SPECS/xorg-x11-drv-xrdp.spec.in
@@ -14,7 +14,7 @@ URL:          http://www.xrdp.org/
 Source0:       %%GH_ACCOUNT%%-%%GH_PROJECT%%-%%GH_COMMIT%%.tar.gz

 # Dependencies don't vary depending on build options
-Requires:      xorg-x11-server-Xorg
+BuildRequires: xorg-x11-server-Xorg
 BuildRequires: automake
 BuildRequires: autoconf
 BuildRequires: libtool
```

> This nosuid Xrdp binary creation should probably be moved to rpm installation script so X version is always consistent with the version on the host.

It makes sense. I'll take your way. Thanks for your advice.

**Comment by metalefty** [comment]
I've pushed to develop branch.
