### ISSUE TITLE
WRKWRC is not defined

### ISSUE THREAD

**Issue by proski** [metalefty/X11RDP-RH-Matic#32]
`calculate_version_num()` refers to an undefined variable `WRKWRC`. I assume it was meant to be WRKSRC, but the source code would not make sense to me even with that substitution.

Why should `${SOURCE_DIR}/${DISTFILE}` be unpacked if and only if `${WRKDIR}/${WRKWRC}` exists? The opposite logic would make sense to me - unpack the tarball unless the unpacked source exists.

Ideally, there should be no conditional there. The build system should ensure that the directory in question always (or never) exists.

The issue exists in the current revision (1a1d1774) and can be traced back to revision aa9d93f4

**Comment by metalefty** [comment]
Yes, WRKWRC is a typo of WRKSRC.  I should have tested undefined variables. I tried `set -u` to detect reference of undefined variables but it overkills. I'll use it only in development test run.  Thanks.

The logic was unintendedly opposite.  I've already fixed it but it can be cleaned up.

**Comment by metalefty** [comment]
I did cleanup in #33. Here's what I intended to do.

**Comment by metalefty** [comment]
Fixed in develop branch.
