### ISSUE TITLE
Build stage fails

### ISSUE THREAD

**Issue by swain-d** [metalefty/X11RDP-RH-Matic#37]
I'm currently unable to install using the script. The output from the build.log is:

`Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.duFVwH
+ umask 022
+ cd /home/dswain/rpmbuild/BUILD
+ cd /home/dswain/rpmbuild/BUILD
+ rm -rf neutrinolabs-xrdp-93c55e5
+ /usr/bin/gzip -dc /home/dswain/rpmbuild/SOURCES/neutrinolabs-xrdp-93c55e5.tar.gz
+ /usr/bin/tar -xf -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd neutrinolabs-xrdp-93c55e5
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ grep -q param0 sesman/sesman.ini
+ echo 'Patch #0 (sesman.ini.master.patch):'
Patch #0 (sesman.ini.master.patch):
+ /usr/bin/cat /home/dswain/rpmbuild/SOURCES/sesman.ini.master.patch
+ /usr/bin/patch -p0 --fuzz=0
patching file sesman/sesman.ini
Hunk #1 FAILED at 81.
1 out of 1 hunk FAILED -- saving rejects to file sesman/sesman.ini.rej
error: Bad exit status from /var/tmp/rpm-tmp.duFVwH (%prep)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.duFVwH (%prep)
`

**Comment by metalefty** [comment]
I'm back from new year's vacation. I started to fix it.

**Comment by Michel-5** [comment]
i'm also unable to install with the script. I als got the same error.

i'm running the system on Clear OS (RHEL based).

cat /etc/centos-release
ClearOS release 7.2.0 (Final) 

cat /etc/redhat-release
ClearOS release 7.2.0 (Final) 

When i run "sh X11RDP-RH-Matic.sh"  i get the follow error:
Building RPMs started, please be patient... 
Do the following command to see build progress.
	$ tail -f /tmp/tmp.VuOXUuJn7v.X11RDP-RH-Matic/build.log
Building xrdp... 

Oops, something going wrong around line: 284
See logs to get further information:
/tmp/tmp.VuOXUuJn7v.X11RDP-RH-Matic/build.log
/tmp/tmp.VuOXUuJn7v.X11RDP-RH-Matic/sudo.log
/tmp/tmp.VuOXUuJn7v.X11RDP-RH-Matic/yum.log
Exiting...

Only the build.log has output:
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.NavkHL
+ umask 022
+ cd /home/supervisor/rpmbuild/BUILD
+ cd /home/supervisor/rpmbuild/BUILD
+ rm -rf neutrinolabs-xrdp-93c55e5
+ /usr/bin/gzip -dc /home/supervisor/rpmbuild/SOURCES/neutrinolabs-xrdp-93c55e5.tar.gz
+ /usr/bin/tar -xf -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd neutrinolabs-xrdp-93c55e5
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ grep -q param0 sesman/sesman.ini
+ echo 'Patch #0 (sesman.ini.master.patch):'
Patch #0 (sesman.ini.master.patch):
+ /usr/bin/cat /home/supervisor/rpmbuild/SOURCES/sesman.ini.master.patch
+ /usr/bin/patch -p0 --fuzz=0
patching file sesman/sesman.ini
Hunk #1 FAILED at 81.
1 out of 1 hunk FAILED -- saving rejects to file sesman/sesman.ini.rej
error: Bad exit status from /var/tmp/rpm-tmp.NavkHL (%prep)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.NavkHL (%prep)

I hope there is a solution soon for this problem.

**Comment by metalefty** [comment]
Fixed in develop branch. Could you test?

**Comment by swain-d** [comment]
I can confirm that this has been fixed in the develop branch. Other issues arise post-installation, which can be addressed in another issue.

**Comment by metalefty** [comment]
Ok, closing this.
