### ISSUE TITLE
error building x11rdp rpms on Centos 7

### ISSUE THREAD

**Issue by ecoutinho** [metalefty/X11RDP-RH-Matic#39]
Hi,

Thanks for writing this utility. While building X11rdp rpms on Centos 7, I get this error:

> \+ cd /home/centos/rpmbuild/BUILD
> \+ /usr/bin/rm -rf /home/centos/rpmbuild/BUILD
> \+ /usr/bin/mkdir -p /home/centos/rpmbuild/BUILD/opt/X11rdp
> \+ /usr/bin/cp -rp /opt/X11rdp/bin /opt/X11rdp/etc /opt/X11rdp/include /opt/X11rdp/lib /opt/X11rdp/man /opt/X11rdp/share /opt/X11rdp/var /home/centos/rpmbuild/BUILD/opt/X11rdp
> \+ find /home/centos/rpmbuild/BUILD '!' -perm -u+w -exec /usr/bin/chmod u+w '{}' ';'
> find: failed to save initial working directory: No such file or directory

This happens because the build script cds into BUILD directory, and then removes it. When it creates it, it will be on another inode. It could be solved by removing just X11rdp directory. On _SPECS/x11rdp.spec.in_ change to:

> %build
> %{__rm} -rf %{_builddir}%%X11RDPBASE%%

Then another error occurs:

> error: Bad file: /home/centos/rpmbuild/SOURCES/buildx_patch.diff: No such file or directory

As there's no _buildx_patch.diff_ file, on _SPECS/x11rdp.spec.in_ remove the line

> Patch0:         buildx_patch.diff

Thanks

**Comment by metalefty** [comment]
Merged your changes, thanks!
