### ISSUE TITLE
sudo

### ISSUE THREAD

**Issue by ToddAndMargo** [metalefty/X11RDP-RH-Matic#41]
Would you put in your documentation on the code page what the requirements are to get past the sudo error that your user is not allowed to run sudo commands

           Sorry, user todd may not run sudo on rn4.

And it would be sweet if you ditched sudo and favor "su", which would cure the issue

**Comment by metalefty** [comment]
OK, I'll add the user must be able to gain root privilege via sudo. But I never support running this utility in root privilege by design.

**Comment by ToddAndMargo** [comment]
I have root privileges.   What do I have to do to visudo to allow my user past this annoying error?

**Comment by metalefty** [comment]
Using sudo is the only option.  Add this to sudoers.
```
yourusername ALL=(ALL) ALL
```

**Comment by ToddAndMargo** [comment]
that isn't real secure!  But I will take it back out afterwards.  Any chance of using su instead?
And thank you!  Please add this to your documentation

**Comment by metalefty** [comment]
I showed you that as an example. Of course you can use secure configuration for sudo. You can change it as you want. But I never support su because not all command executed in RH-Matic requires root privilege.
