### ISSUE TITLE
RHEL 7.1 fails to locate neutrinolabs-xrdp-*/xorg/server during compile of xorg

### ISSUE THREAD

**Issue by fang64** [metalefty/X11RDP-RH-Matic#8]
X11RDP-RH-Matic fails to compile xorg-x11-drv-rdp with "--with-xorg-driver --nox11rdp" options being passed. 

I've attached the output:
http://fpaste.org/203654/27441257/

**Comment by metalefty** [comment]
Containts of xorg/server directory are moved to xorgxrdp directory and now provided as git submodule.  I'm working on applying this change.

**Comment by metalefty** [comment]
Fixed by 0d85f3c2.
